Add JS to have all pages in index.html
teifler/quiz-app pull request #13
Opened 2022-01-29 12:11 UTC by teifler

2022-01-29 21:08 UTC, ttaannjjaa requested changes
Awesome work 👍

2022-01-29 21:08 UTC, ttaannjjaa commented on index.html
> +          <br />Lorem ipsum, dolor sit amet consectetur adipisicing elit.
i believe, that you dont need `<br />` here as this should be included in the default function of `details`and `summary`

2022-01-29 21:08 UTC, ttaannjjaa commented on index.html
> +        <ul class="app-card__list">
here i think, adding `role="list"` to the `ul`-tag is wanted coz of accessibility reasons

2022-01-29 21:08 UTC, ttaannjjaa commented on index.html
> +        <ul class="app-card__list">
if you agree with my comment above, here is another `details/summary`and `ul`tag 🙂 and some more following

2022-01-29 21:08 UTC, ttaannjjaa commented on index.html
> +        <label class="app-create__label" for="add-question" id="yolo"
i am curious, for what you need the id="yolo"

2022-01-29 21:08 UTC, ttaannjjaa commented on index.html
> +          <br />
i believe for semantic html the `br`tag shouldn`t used for styling, better to use CSS

2022-01-29 21:08 UTC, ttaannjjaa commented on index.html
> +          <br />
another `br`😊

2022-01-29 21:08 UTC, ttaannjjaa commented on index.html
> +          <ul role="list" class="profile__skills-flex no-bul">
😊👍

2022-01-29 21:08 UTC, ttaannjjaa commented on index.html
> +    <!-- LOGGED OUT -->
Very cool, that you added this all 👍

2022-01-29 21:08 UTC, ttaannjjaa commented on index.html
> +        <label for="user-login"
i think you changed here something and you mean now here `for="user-email"`

2022-01-29 21:08 UTC, ttaannjjaa commented on index.html
> +          <br />
another `<br>`

2022-01-29 21:08 UTC, ttaannjjaa commented on index.html
> +          <input
i think, each of the input fields needs its own label, so here should be added one with the `for`-Attribut = "user-pass"

2022-01-29 21:08 UTC, ttaannjjaa commented on index.html
> +            <img alt="" src="../../images/home.svg" width="48" height="48" />
width/height of the other img are still 40/40 , just as a reminder for you

2022-01-29 21:08 UTC, ttaannjjaa commented on js/navigation.js
> +    console.log('DRINNEN BOOKMARK' + buttonBookmarks);
probably it works and you don't need this any more - i like also to use it since you have told me :-)

2022-01-29 21:08 UTC, ttaannjjaa commented on js/textfieldCounter.js
> +  questionInputElement?.addEventListener('input', event => {
i think, you dont need the argument `event`here as you dont use it in the function itself, you can make the call anonymous with ()

2022-01-29 21:08 UTC, ttaannjjaa commented on js/textfieldCounter.js
> +    const result = 200 - questionInputElement.value.length;
awesome function - i like it very much

2022-01-29 21:08 UTC, ttaannjjaa commented on profile.html
> -      <section class="app-profile">
i think this all is now in index.html, so i wont look at it exactly

2022-01-29 21:08 UTC, ttaannjjaa commented on styles/components/app-create.css
> +  width: 100vw;
i wondering whether this is an advantage 🤔

2022-01-29 21:08 UTC, ttaannjjaa commented on styles/components/app-create.css
> +.app-create__label {
good idea - maybe i will make it the same in my code :-)

2022-01-29 21:08 UTC, ttaannjjaa commented on styles/components/app-create.html
> -        <label for="add-question">Please enter your question: </label>
also in index.html i think

2022-01-29 21:08 UTC, ttaannjjaa commented on styles/components/app-profile.css
> +  gap: 500px;
that looks a lot -maybe it could cause responsive design problems - what do you think?

2022-01-29 21:08 UTC, ttaannjjaa commented on styles/utility.css
> +.flex {
maybe a name of the class like `.flexcolumn` would clarify a little bit here

2022-01-30 09:39 UTC, teifler commented on index.html
> +          <br />Lorem ipsum, dolor sit amet consectetur adipisicing elit.
Thank you very much for the review. I need that <br /> otherwise the text will be still inline with show answer.

2022-01-30 09:47 UTC, teifler commented on index.html
> +        <label class="app-create__label" for="add-question" id="yolo"
Thank you, was a old ID for test purposes, I removed it.

2022-01-30 13:54 UTC, teifler commented on index.html
> +        <ul class="app-card__list">
Removed :)

2022-01-30 13:55 UTC, merged